INSERT INTO `companies` (`name`, `class`) VALUES
('Smartwings', 1),
('Ryanair', 1),
('KLM', 3),
('China Airlines', 2),
('Wizz Air', 1),
('Emirates', 4),
('British Airways', 2),
('Air France', 3),
('Aeroflot', 2),
('American Airlines', 2),
('Lufthansa', 3),
('Turkish Airlines', 2),
('ČSA', 2),
('Flydubai', 2),
('Etihad Airways', 3),
('Ethiopean Airlines', 1),
('Air Canada', 2),
('Delta Air Lines', 2),
('LOT', 2),
('Swiss', 4),
('Pan Am', 2),
('Singapure Airlines', 4),
('ANA', 1),
('United Airlines', 2),
('Southwest Airlines', 1),
('IAG', 2),
('Qantas', 3),
('Japan Airlines', 2),
('Malaysia Airlines', 2),
('Qatar Airways', 4);